services:
  bot:
    build: .
    container_name: trade-bot
    env_file:
      - .env.docker
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      prometheus:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs  # Копируем логи из контейнера на ПК
    networks:
      - trade-network

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-db}" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - trade-network

  redis:
    image: redis:8-alpine
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
    #    volumes:
    #      - ./redisdata:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "password", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - trade-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/etc:/etc/prometheus/
      - ./prometheus/data:/prometheus
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - ${PROMETHEUS_DOOR_PORT}:9090
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - trade-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    networks:
      - trade-network

networks:
  trade-network:
    driver: bridge

volumes:
  pgdata:
  grafana-storage: { }
